spring:
  application:
    name: delivery
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
