spring:
  datasource:
    url: jdbc:h2:mem:temp;DB_CLOSE_DELAY=-1;INIT=RUNSCRIPT FROM 'classpath:sql/schema.sql'\;RUNSCRIPT FROM 'classpath:sql/data.sql'
    username: delivery
    password: 123456
    driver-class-name: org.h2.Driver
    initialize: true
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-other: true
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
